"""Seed Neo4j with realistic graph data for notebook demonstrations."""

from neo4j import GraphDatabase

driver = GraphDatabase.driver("bolt://localhost:7687", auth=("neo4j", "neo4jneo4j"))

# Clear existing data
with driver.session() as s:
    s.run("MATCH (n) DETACH DELETE n")
    print("Cleared existing data")

# ============================================================
# VERSION v2.3.0
# ============================================================
V1_CLASSES = """
CREATE (btm:Class {name: 'BaseTestMethod', qualifiedName: 'framework.runtime.BaseTestMethod', category: 'Framework', gitTag: 'v2.3.0', visibility: 'public', isAbstract: true})
CREATE (tcb:Class {name: 'TestCaseBase', qualifiedName: 'framework.runtime.TestCaseBase', category: 'Framework', gitTag: 'v2.3.0', visibility: 'public', isAbstract: true})
CREATE (tlm:Class {name: 'TestListManager', qualifiedName: 'framework.runtime.TestListManager', category: 'Framework', gitTag: 'v2.3.0', visibility: 'public', isAbstract: false})
CREATE (tl:Class {name: 'TestList', qualifiedName: 'framework.runtime.TestList', category: 'Framework', gitTag: 'v2.3.0', visibility: 'public', isAbstract: false})
CREATE (cl:Class {name: 'ConfigLoader', qualifiedName: 'framework.config.ConfigLoader', category: 'Configuration', gitTag: 'v2.3.0', visibility: 'public', isAbstract: false})
CREATE (cb:Class {name: 'ConfigBlock', qualifiedName: 'framework.config.ConfigBlock', category: 'Configuration', gitTag: 'v2.3.0', visibility: 'public', isAbstract: false})
CREATE (lca:Class {name: 'LevelChangeAction', qualifiedName: 'framework.actions.LevelChangeAction', category: 'Action', gitTag: 'v2.3.0', visibility: 'public', isAbstract: false})
CREATE (sra:Class {name: 'SetupRestoreAction', qualifiedName: 'framework.actions.SetupRestoreAction', category: 'Action', gitTag: 'v2.3.0', visibility: 'public', isAbstract: false})
CREATE (etm:Class {name: 'ExampleTestMethod', qualifiedName: 'testmethod.ExampleTestMethod', category: 'TestMethod', gitTag: 'v2.3.0', visibility: 'public', isAbstract: false})
CREATE (vtm:Class {name: 'VoltageMarginTest', qualifiedName: 'testmethod.VoltageMarginTest', category: 'TestMethod', gitTag: 'v2.3.0', visibility: 'public', isAbstract: false})
CREATE (ftm:Class {name: 'FrequencySweepTest', qualifiedName: 'testmethod.FrequencySweepTest', category: 'TestMethod', gitTag: 'v2.3.0', visibility: 'public', isAbstract: false})
CREATE (ptm:Class {name: 'PowerSequenceTest', qualifiedName: 'testmethod.PowerSequenceTest', category: 'TestMethod', gitTag: 'v2.3.0', visibility: 'public', isAbstract: false})
CREATE (ltm:Class {name: 'LeakageCurrentTest', qualifiedName: 'testmethod.LeakageCurrentTest', category: 'TestMethod', gitTag: 'v2.3.0', visibility: 'public', isAbstract: false})
CREATE (dftc:Class {name: 'DcFunctionalTestCase', qualifiedName: 'testcases.DcFunctionalTestCase', category: 'TestCase', gitTag: 'v2.3.0', visibility: 'public', isAbstract: false})
CREATE (actc:Class {name: 'AcTimingTestCase', qualifiedName: 'testcases.AcTimingTestCase', category: 'TestCase', gitTag: 'v2.3.0', visibility: 'public', isAbstract: false})
CREATE (sgtc:Class {name: 'ShmooGridTestCase', qualifiedName: 'testcases.ShmooGridTestCase', category: 'TestCase', gitTag: 'v2.3.0', visibility: 'public', isAbstract: false})
CREATE (pltc:Class {name: 'PowerLimitTestCase', qualifiedName: 'testcases.PowerLimitTestCase', category: 'TestCase', gitTag: 'v2.3.0', visibility: 'public', isAbstract: false})

CREATE (etm)-[:EXTENDS]->(btm)
CREATE (vtm)-[:EXTENDS]->(btm)
CREATE (ftm)-[:EXTENDS]->(btm)
CREATE (ptm)-[:EXTENDS]->(btm)
CREATE (ltm)-[:EXTENDS]->(btm)
CREATE (dftc)-[:EXTENDS]->(tcb)
CREATE (actc)-[:EXTENDS]->(tcb)
CREATE (sgtc)-[:EXTENDS]->(tcb)
CREATE (pltc)-[:EXTENDS]->(tcb)

CREATE (btm)-[:DEFINES_METHOD]->(:Method {name: 'defineTestSequences', visibility: 'protected', returnType: 'void'})
CREATE (btm)-[:DEFINES_METHOD]->(:Method {name: 'initialize', visibility: 'public', returnType: 'void'})
CREATE (btm)-[:DEFINES_METHOD]->(:Method {name: 'cleanup', visibility: 'public', returnType: 'void'})
CREATE (etm)-[:DEFINES_METHOD]->(:Method {name: 'defineTestSequences', visibility: 'protected', returnType: 'void'})
CREATE (etm)-[:DEFINES_METHOD]->(:Method {name: 'loadModuleConfig', visibility: 'private', returnType: 'ConfigBlock'})
CREATE (vtm)-[:DEFINES_METHOD]->(:Method {name: 'defineTestSequences', visibility: 'protected', returnType: 'void'})
CREATE (vtm)-[:DEFINES_METHOD]->(:Method {name: 'sweepVoltage', visibility: 'private', returnType: 'double[]'})
CREATE (vtm)-[:DEFINES_METHOD]->(:Method {name: 'evaluateMargin', visibility: 'private', returnType: 'boolean'})
CREATE (ftm)-[:DEFINES_METHOD]->(:Method {name: 'defineTestSequences', visibility: 'protected', returnType: 'void'})
CREATE (ftm)-[:DEFINES_METHOD]->(:Method {name: 'runFrequencySweep', visibility: 'private', returnType: 'Map'})
CREATE (ftm)-[:DEFINES_METHOD]->(:Method {name: 'calculateJitter', visibility: 'private', returnType: 'double'})
CREATE (ftm)-[:DEFINES_METHOD]->(:Method {name: 'reportResults', visibility: 'protected', returnType: 'void'})
CREATE (ptm)-[:DEFINES_METHOD]->(:Method {name: 'defineTestSequences', visibility: 'protected', returnType: 'void'})
CREATE (ptm)-[:DEFINES_METHOD]->(:Method {name: 'sequencePowerRails', visibility: 'private', returnType: 'void'})
CREATE (ltm)-[:DEFINES_METHOD]->(:Method {name: 'defineTestSequences', visibility: 'protected', returnType: 'void'})
CREATE (ltm)-[:DEFINES_METHOD]->(:Method {name: 'measureLeakage', visibility: 'private', returnType: 'double'})
CREATE (tcb)-[:DEFINES_METHOD]->(:Method {name: 'defineTestSequence', visibility: 'public', returnType: 'void'})
CREATE (tcb)-[:DEFINES_METHOD]->(:Method {name: 'execute', visibility: 'public', returnType: 'TestResult'})
CREATE (cl)-[:DEFINES_METHOD]->(:Method {name: 'load', visibility: 'public', returnType: 'ConfigBlock'})
CREATE (cl)-[:DEFINES_METHOD]->(:Method {name: 'validate', visibility: 'private', returnType: 'boolean'})
CREATE (tlm)-[:DEFINES_METHOD]->(:Method {name: 'create', visibility: 'public', returnType: 'TestList'})
CREATE (tlm)-[:DEFINES_METHOD]->(:Method {name: 'getActiveList', visibility: 'public', returnType: 'TestList'})
CREATE (tl)-[:DEFINES_METHOD]->(:Method {name: 'setupBegin', visibility: 'public', returnType: 'TestList'})
CREATE (tl)-[:DEFINES_METHOD]->(:Method {name: 'setupEnd', visibility: 'public', returnType: 'TestList'})
CREATE (tl)-[:DEFINES_METHOD]->(:Method {name: 'addTestCase', visibility: 'public', returnType: 'TestCaseBase'})
CREATE (tl)-[:DEFINES_METHOD]->(:Method {name: 'addAction', visibility: 'public', returnType: 'TestList'})
CREATE (dftc)-[:DEFINES_METHOD]->(:Method {name: 'defineTestSequence', visibility: 'public', returnType: 'void'})
CREATE (dftc)-[:DEFINES_METHOD]->(:Method {name: 'measureDcParameters', visibility: 'private', returnType: 'double[]'})
CREATE (actc)-[:DEFINES_METHOD]->(:Method {name: 'defineTestSequence', visibility: 'public', returnType: 'void'})
CREATE (actc)-[:DEFINES_METHOD]->(:Method {name: 'measureTimingMargin', visibility: 'private', returnType: 'double'})
CREATE (sgtc)-[:DEFINES_METHOD]->(:Method {name: 'defineTestSequence', visibility: 'public', returnType: 'void'})
CREATE (sgtc)-[:DEFINES_METHOD]->(:Method {name: 'generateShmooPlot', visibility: 'private', returnType: 'byte[]'})
CREATE (pltc)-[:DEFINES_METHOD]->(:Method {name: 'defineTestSequence', visibility: 'public', returnType: 'void'})

CREATE (dep1:ExternalDependency {name: 'core-runtime.jar'})
CREATE (dep2:ExternalDependency {name: 'config-support.jar'})
CREATE (dep3:ExternalDependency {name: 'analysis-support.jar'})
CREATE (dep4:ExternalDependency {name: 'reporting-support.jar'})

CREATE (etm)-[:DEPENDS_ON]->(dep1)
CREATE (etm)-[:DEPENDS_ON]->(dep2)
CREATE (vtm)-[:DEPENDS_ON]->(dep1)
CREATE (vtm)-[:DEPENDS_ON]->(dep3)
CREATE (vtm)-[:DEPENDS_ON]->(dep4)
CREATE (ftm)-[:DEPENDS_ON]->(dep1)
CREATE (ftm)-[:DEPENDS_ON]->(dep3)
CREATE (ftm)-[:DEPENDS_ON]->(dep4)
CREATE (ptm)-[:DEPENDS_ON]->(dep1)
CREATE (ptm)-[:DEPENDS_ON]->(dep2)
CREATE (ltm)-[:DEPENDS_ON]->(dep1)
CREATE (ltm)-[:DEPENDS_ON]->(dep3)
CREATE (cl)-[:DEPENDS_ON]->(dep2)
CREATE (dftc)-[:DEPENDS_ON]->(dep1)
CREATE (dftc)-[:DEPENDS_ON]->(dep3)
CREATE (actc)-[:DEPENDS_ON]->(dep1)
CREATE (actc)-[:DEPENDS_ON]->(dep3)
CREATE (sgtc)-[:DEPENDS_ON]->(dep1)
CREATE (sgtc)-[:DEPENDS_ON]->(dep4)

CREATE (i1:Import {path: 'framework.actions.LevelChangeAction'})
CREATE (i2:Import {path: 'framework.config.ConfigBlock'})
CREATE (i3:Import {path: 'framework.config.ConfigLoader'})
CREATE (i4:Import {path: 'framework.runtime.BaseTestMethod'})
CREATE (i5:Import {path: 'framework.runtime.TestCaseBase'})
CREATE (i6:Import {path: 'framework.runtime.TestList'})
CREATE (i7:Import {path: 'framework.runtime.TestListManager'})
CREATE (i8:Import {path: 'java.util.List'})
CREATE (i9:Import {path: 'java.util.Map'})
CREATE (i10:Import {path: 'framework.actions.SetupRestoreAction'})

CREATE (etm)-[:IMPORTS]->(i1)
CREATE (etm)-[:IMPORTS]->(i2)
CREATE (etm)-[:IMPORTS]->(i3)
CREATE (etm)-[:IMPORTS]->(i4)
CREATE (etm)-[:IMPORTS]->(i6)
CREATE (etm)-[:IMPORTS]->(i7)
CREATE (etm)-[:IMPORTS]->(i8)
CREATE (vtm)-[:IMPORTS]->(i1)
CREATE (vtm)-[:IMPORTS]->(i2)
CREATE (vtm)-[:IMPORTS]->(i3)
CREATE (vtm)-[:IMPORTS]->(i4)
CREATE (vtm)-[:IMPORTS]->(i8)
CREATE (ftm)-[:IMPORTS]->(i1)
CREATE (ftm)-[:IMPORTS]->(i2)
CREATE (ftm)-[:IMPORTS]->(i3)
CREATE (ftm)-[:IMPORTS]->(i4)
CREATE (ftm)-[:IMPORTS]->(i8)
CREATE (ftm)-[:IMPORTS]->(i9)
CREATE (ptm)-[:IMPORTS]->(i1)
CREATE (ptm)-[:IMPORTS]->(i4)
CREATE (ptm)-[:IMPORTS]->(i10)
CREATE (ltm)-[:IMPORTS]->(i2)
CREATE (ltm)-[:IMPORTS]->(i3)
CREATE (ltm)-[:IMPORTS]->(i4)
CREATE (dftc)-[:IMPORTS]->(i5)
CREATE (actc)-[:IMPORTS]->(i5)
CREATE (sgtc)-[:IMPORTS]->(i5)
CREATE (pltc)-[:IMPORTS]->(i5)

CREATE (md1:MarkdownFile {path: 'docs/ExampleTestMethod.md'})
CREATE (md2:MarkdownFile {path: 'docs/VoltageMarginTest.md'})
CREATE (md3:MarkdownFile {path: 'docs/BaseTestMethod.md'})
CREATE (md4:MarkdownFile {path: 'docs/ConfigLoader.md'})
CREATE (md5:MarkdownFile {path: 'docs/FrequencySweepTest.md'})

CREATE (md1)-[:RESOLVES_TO]->(etm)
CREATE (md2)-[:RESOLVES_TO]->(vtm)
CREATE (md3)-[:RESOLVES_TO]->(btm)
CREATE (md4)-[:RESOLVES_TO]->(cl)
CREATE (md5)-[:RESOLVES_TO]->(ftm)
"""

with driver.session() as s:
    s.run(V1_CLASSES)
    print("Seeded v2.3.0 data")

# ============================================================
# VERSION v2.4.0 (additive - new version nodes)
# ============================================================
V2_CLASSES = """
CREATE (btm2:Class {name: 'BaseTestMethod', qualifiedName: 'framework.runtime.BaseTestMethod', category: 'Framework', gitTag: 'v2.4.0', visibility: 'public', isAbstract: true})
CREATE (tcb2:Class {name: 'TestCaseBase', qualifiedName: 'framework.runtime.TestCaseBase', category: 'Framework', gitTag: 'v2.4.0', visibility: 'public', isAbstract: true})
CREATE (tlm2:Class {name: 'TestListManager', qualifiedName: 'framework.runtime.TestListManager', category: 'Framework', gitTag: 'v2.4.0', visibility: 'public', isAbstract: false})
CREATE (etm2:Class {name: 'ExampleTestMethod', qualifiedName: 'testmethod.ExampleTestMethod', category: 'TestMethod', gitTag: 'v2.4.0', visibility: 'public', isAbstract: false})
CREATE (vtm2:Class {name: 'VoltageMarginTest', qualifiedName: 'testmethod.VoltageMarginTest', category: 'TestMethod', gitTag: 'v2.4.0', visibility: 'public', isAbstract: false})
CREATE (ftm2:Class {name: 'FrequencySweepTest', qualifiedName: 'testmethod.FrequencySweepTest', category: 'TestMethod', gitTag: 'v2.4.0', visibility: 'public', isAbstract: false})
CREATE (ptm2:Class {name: 'PowerSequenceTest', qualifiedName: 'testmethod.PowerSequenceTest', category: 'TestMethod', gitTag: 'v2.4.0', visibility: 'public', isAbstract: false})
CREATE (ltm2:Class {name: 'LeakageCurrentTest', qualifiedName: 'testmethod.LeakageCurrentTest', category: 'TestMethod', gitTag: 'v2.4.0', visibility: 'public', isAbstract: false})
CREATE (jtm2:Class {name: 'JtagBoundaryTest', qualifiedName: 'testmethod.JtagBoundaryTest', category: 'TestMethod', gitTag: 'v2.4.0', visibility: 'public', isAbstract: false})
CREATE (sttm2:Class {name: 'SignalTimingTest', qualifiedName: 'testmethod.SignalTimingTest', category: 'TestMethod', gitTag: 'v2.4.0', visibility: 'public', isAbstract: false})
CREATE (tc2:Class {name: 'ThermalCycleTestCase', qualifiedName: 'testcases.ThermalCycleTestCase', category: 'TestCase', gitTag: 'v2.4.0', visibility: 'public', isAbstract: false})

CREATE (etm2)-[:EXTENDS]->(btm2)
CREATE (vtm2)-[:EXTENDS]->(btm2)
CREATE (ftm2)-[:EXTENDS]->(btm2)
CREATE (ptm2)-[:EXTENDS]->(btm2)
CREATE (ltm2)-[:EXTENDS]->(btm2)
CREATE (jtm2)-[:EXTENDS]->(btm2)
CREATE (sttm2)-[:EXTENDS]->(btm2)
CREATE (tc2)-[:EXTENDS]->(tcb2)

CREATE (jtm2)-[:DEFINES_METHOD]->(:Method {name: 'defineTestSequences', visibility: 'protected', returnType: 'void'})
CREATE (jtm2)-[:DEFINES_METHOD]->(:Method {name: 'scanBoundary', visibility: 'private', returnType: 'int[]'})
CREATE (sttm2)-[:DEFINES_METHOD]->(:Method {name: 'defineTestSequences', visibility: 'protected', returnType: 'void'})
CREATE (sttm2)-[:DEFINES_METHOD]->(:Method {name: 'measureSetupHold', visibility: 'private', returnType: 'double[]'})
CREATE (tc2)-[:DEFINES_METHOD]->(:Method {name: 'defineTestSequence', visibility: 'public', returnType: 'void'})
"""

with driver.session() as s:
    s.run(V2_CLASSES)
    print("Seeded v2.4.0 data")

# Verify counts
with driver.session() as s:
    r = s.run("MATCH (n) RETURN labels(n)[0] AS label, count(*) AS cnt ORDER BY cnt DESC")
    print("\n=== Final Node Counts ===")
    for row in r:
        print(f"  {row['label']}: {row['cnt']}")

    r2 = s.run("MATCH ()-[r]->() RETURN type(r) AS rel, count(*) AS cnt ORDER BY cnt DESC")
    print("\n=== Relationship Counts ===")
    for row in r2:
        print(f"  {row['rel']}: {row['cnt']}")

driver.close()
print("\nSeed complete!")
